# example netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"


[[dev]]
  targetPort = 3000
  framework = "create-react-app"

